# Site settings
name: YangEnneng
description: "如果真的相信什么，就要用尽全力去让它发生。"
url: "http://yangenneng.cn/"


# Delete the lines you don't need
# about 5 elements are recomended
github_username:  YEN-GitHub
codepen_username: 
facebook_username: 
vk_username: 
twitter_username: 
google_plus_username: 
linkedin_username: 
vine_username:
instagram_username:
flickr_username:
steam_username:
soundcloud_username:
stack_of_username:
reddit_username:
medium_username:
tumblr_username:
weibo_username: yen_xlwb
lastfm_username:
blog_url: "/blog"
email:1274491995@qq.com
public_key_url: "http://yangenneng.cn/"


avatar: yes
# avatar_img_path: "imgs/avatar.jpg""
# You can link to your GitHub image. That way it will get updated
# automatically whenever you change your GitHub profile picture
avatar_img_path: "https://avatars1.githubusercontent.com/u/19388092?v=3&s=460"


front_img: yes
front_img_path: "imgs/background.jpg"
# front_img_path: "https://external.url/image.jpg"


favicon_img: yes
favicon_img_path: "imgs/favicon.ico"
# favicon_img_path: "https://external.url/favicon.ico"


# Build settings
markdown: kramdown
permalink: pretty
